### PR TITLE
[ADD] Use cuban vaccine prophylaxis and medical product

### PR DESCRIPTION
**Pull request by yvcruz**
Add in valuesets files `vaccine-prophylaxys.json` and `vaccine-medical-product.json`, the cuban medical treatments for covid-19 (Soberana 02, Abdala);
Add in valuesets file `vaccine-mah-manf.json`, the manufactures of the cuban vaccines;

### CODE REVIEW

**Comment by gabywh** [comment]
Thanks for your input.
I will pass it on to the Semantic Sub-Group who define the valuesets.

**Comment by kruzikh** [comment]
I will bring this proposal to the Semantic Subgroup today. According to my quick search cuban vaccines has not been approved by EMA nor by FDA or WHO, which is one of inclusion criteria for EU vaccines value set.  It would be helpful if we will have information about the reasons why you are proposing to add them.

**Comment by jschlyter** [comment]
@yvcruz there's also the option to define your own HCERT payload just as EU Digital Covid Certificate v1 (`eu_dcc_v1`). The HCERT container was designed with this in mind.

**Comment by yvcruz** [comment]
> I will bring this proposal to the Semantic Subgroup today. According to my quick search cuban vaccines has not been approved by EMA nor by FDA or WHO, which is one of inclusion criteria for EU vaccines value set. It would be helpful if we will have information about the reasons why you are proposing to add them.

At this time, all the steps are being taken to have Cuban vaccines recognized and approved by the EU and WHO, and for the purpose of creating green certificates to facilitate the travel of vaccinated people to the EU. We are using this schema repository to fine-tune health certificate creation.
Greetings

**Comment by yvcruz** [comment]
> @yvcruz there's also the option to define your own HCERT payload just as EU Digital Covid Certificate v1 (`eu_dcc_v1`). The HCERT container was designed with this in mind.

That was the first step, we already have alternatives that run throughout the national territory, and we are adjusting our solution to different scenarios.
Greetings

**Comment by kruzikh** [comment]
@yvcruz could you formulate an official request from a EU member state and address it to the Chair of the SgS Stefanie.Weber@bfarm.de? This would help facilitating discussion in the SgS. Semantically, we can add new vaccines to the value set, however acceptance of such certificate at boarder is purely on the member states' decision. At the other hand, as I wrote, there are several inclusion criteria for the entries and we need sort of justification on each proposal.

**Comment by yvcruz** [comment]
Yes, we will go through all the steps to make inclusion effective. This is essential in order to add the test cases of the structures that your standard defines. And validate the effectiveness of our issuer model.
Thank you

**Comment by ryanbnl** [comment]
@yvcruz @kruzikh is there an update for this, or can I close it?

**Comment by ryanbnl** [comment]
I'll close this for now on the assumption that there is no update / it's not needed.

**Comment by gabywh** [comment]
Disclaimer: I haven't read the rest of the posts on this topic, just the
last one, as I'm giving a tutorial on AI at the University ATM...

Summary: The valuesets should be *removed* from ehn-dcc-schema.

IIRC Meinte should have updated the README.md in ehn-dcc-schema many months
ago already to say "please look at ehn-dcc-valuesets instead of here for
the valuelsets"

My PR for a 1.3.1 would have removed the valuesets in ehn-dcc-schema had it
been applied, which it doesn't seem to have been given this new and IMHO
completely understandable PR from a user/dev perspective

Even though I haven't been on the project for many months I will take a
look at this tonight and look at applying the PR to simply remove the
valuesets from ehn-dcc-schema, as my sympathies are very much with the
end-user devs who should at least be able to expect clarity here.

@Hynek
1. I'll do the change for a 1.3.1 which removes the duplicate  and
2.  Will prepare a 1.3.1 release for.you, which will then need formal
approval from eHN Te h IOP before making the official release. If you still
have the TechIOP meetings Friday morning  you could even raise this issue
and request formal release permission as soon  as tomorrow am

Gaby


Op do 24 feb. 2022 15:44 schreef Ryan Barrett ***@***.***>:

**Comment by ryanbnl** [comment]
There's no need - we're cleaning up the remaining PRs / issues this week as per the internal process :-)

**Pull request closed without merging**
