### PR TITLE
Fixes missing descriptions of "tg" properties in test and recovery groups

### LINKED ISSUE #129: Missing descriptions of "tg" property in test and recovery groups
Currently (schema v1.3.0 and proposed v1.3.1) only "vaccination_entry" has property "tg" containing "description":
```
"vaccination_entry": {
  [...]
  "properties": {
    "tg": {
      "description": "disease or agent targeted",
      "$ref": "#/$defs/disease-agent-targeted"
    },
```
"test_entry" and "recovery_entry" both lack "description" property - only "$ref" is provided:
```
"test_entry": {
  [...]
  "properties": {
    "tg": {
      "$ref": "#/$defs/disease-agent-targeted"
    },
```
When using automated tools that parse schema to provide human-readable form of DCCs using contained descriptions, this omission results in output that has "tg" not described - the schema is not complete for this usage in its published form.
Other properties common to all groups, such as "is" or "ci" already have the same descriptions duplicated in every group, "tg" property having description everywhere would be more consistent than at present when only vaccination group has it.
"test_entry" and "recovery_entry" should contain "tg" with the same description as "vaccination_entry".

### PR DESCRIPTION
**Pull request by Jakub-KK**
Fixes #129

### CODE REVIEW

**Comment by dslmeinte** [comment]
Hi @Jakub-KK ,
Thanks for the PR!
This change can't go into the 1.3.0 release, however. Instead, it should go into a new release branch (1.3.1, probably). I'll have to confer with my eHN colleagues what we're going to do.

**Comment by kruzikh** [comment]
Hi, agree for sure. I presume that once release 1.3.1 will be pushed to main, this change will be visible in all release after 1.3.1 wright?

**Comment by dslmeinte** [comment]
> Hi, agree for sure. I presume that once release 1.3.1 will be pushed to main, this change will be visible in all release after 1.3.1 wright?

That's correct.

**Comment by dslmeinte** [comment]
Hi @Jakub-KK , I changed the PR target to the newly-minted `release/1.3.1` branch. Could you rebase your PR on that branch?

**Comment by Jakub-KK** [comment]
Hi @dslmeinte, I rebased my commit.

**Review by dslmeinte — APPROVED** [review]

**Review by kruzikh — APPROVED** [review]

**Comment by dslmeinte** [comment]
Thanks @Jakub-KK for your contribution! 🙏

**Pull request merged**
